### ISSUE TITLE
Path handling changed in 3.11

### ISSUE THREAD

**Issue by fredemmott** [facebook/hhvm#6678]
```
fred@hhvm-oss-bench:/tmp/out$ cat index.php
<?php
var_dump(ini_get('doc_root'));
fred@hhvm-oss-bench:/tmp/out$ ~/bin/hhvm-dbg-3.10.1 -v Server.SourceRoot= index.php
string(9) "/tmp/out/"
fred@hhvm-oss-bench:/tmp/out$ ~/bin/hhvm-dbg-3.11.0 -v Server.SourceRoot= index.php
string(0) ""
```

Causes 404s and crashes depending on situation, issue merge incoming

**Comment by fredemmott** [comment]
https://github.com/facebook/hhvm/commit/ffff72320447bd0038d397badf44eb9815f6a9c1

**Comment by fredemmott** [comment]
Potential fix (FB: D2771940):

```
diff --git a/fbcode/hphp/runtime/base/runtime-option.cpp b/fbcode/hphp/runtime/base/runtime-option.cpp
--- a/fbcode/hphp/runtime/base/runtime-option.cpp
+++ b/fbcode/hphp/runtime/base/runtime-option.cpp
@@ -1356,9 +1356,12 @@
                  "Server.TLSClientCipherSpec");

     // SourceRoot has been default to: Process::GetCurrentDirectory() + '/'
+    auto defSourceRoot = SourceRoot;
     Config::Bind(SourceRoot, ini, config, "Server.SourceRoot", SourceRoot);
-    string srcRoot = FileUtil::normalizeDir(SourceRoot);
-    if (!srcRoot.empty()) SourceRoot = srcRoot;
+    if (SourceRoot.empty()) {
+      SourceRoot = defSourceRoot;
+    }
+    SourceRoot = FileUtil::normalizeDir(SourceRoot);
     FileCache::SourceRoot = SourceRoot;

     Config::Bind(IncludeSearchPaths, ini, config, "Server.IncludeSearchPaths");
diff --git a/fbcode/hphp/test/slow/ini/source_root_empty.php b/fbcode/hphp/test/slow/ini/source_root_empty.php
new file mode 100644
--- /dev/null
+++ b/fbcode/hphp/test/slow/ini/source_root_empty.php
@@ -0,0 +1,2 @@
+<?php
+var_dump(ini_get("hhvm.server.source_root") === getcwd().'/');
diff --git a/fbcode/hphp/test/slow/ini/source_root_empty.php.expect b/fbcode/hphp/test/slow/ini/source_root_empty.php.expect
new file mode 100644
--- /dev/null
+++ b/fbcode/hphp/test/slow/ini/source_root_empty.php.expect
@@ -0,0 +1,1 @@
+bool(true)
diff --git a/fbcode/hphp/test/slow/ini/source_root_empty.php.ini b/fbcode/hphp/test/slow/ini/source_root_empty.php.ini
new file mode 100644
--- /dev/null
+++ b/fbcode/hphp/test/slow/ini/source_root_empty.php.ini
@@ -0,0 +1,1 @@
+hhvm.server.source_root=
```

**Comment by fredemmott** [comment]
That fixes some issues, but issue still exists for some

**Comment by fredemmott** [comment]
We believe this is fixed.

**Comment by J0WI** [comment]
Just checked the current Nightly. HHVM still crashes over FastCGI on Ubuntu 15.10.
```
HipHop VM 3.12.0-dev (rel)
Compiler: heads/master-0-ge366af94f672e61c32513be55fdc476834c295a8
Repo schema: dadb2f5dcf37fa6f171919587a5e9f40428c0632
```

**Comment by fredemmott** [comment]
@J0WI : that sounds unrelated; this is only known to cause crashes in debug build, and that is a release build. Please file a separate issue with more details.
