### ISSUE TITLE
OS X build broken by homebrew ocaml 4.03 update

### ISSUE THREAD

**Issue by akuseru** [facebook/hhvm#7040]
## Description
attempting a `brew install hhvm` fails. 

I think the errors start with:

```
[  1%] Building CXX object third-party/re2/CMakeFiles/re2.dir/src/util/stringprintf.cc.o
/bin/sh: ocamlbuild: command not found
make[4]: *** [build-hack-native-deps] Error 127
make[3]: *** [_build/hh_server.native] Error 2
make[2]: *** [hphp/hack/CMakeFiles/hack] Error 2
make[1]: *** [hphp/hack/CMakeFiles/hack.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
ocaml 4.03.0 is installed but does not include ocamlbuild. looking at the homebrew repo it looks like ocamlbuild was moved into a separate install. 
so 
`brew install ocamlbuild` 

still errors out. (logs below)

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.11
**Homebrew Version:**   | 0.9.9
**Xcode Version:**      | 7.3.1

**Output of clang -v:**
```
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Build logs:**gist log: https://gist.github.com/anonymous/8f1570a41d9cf90ec5ad9a03add3f11d

**Comment by jwatzman** [comment]
Thanks, I'll look into this at some point. Hopefully we just need to add `ocamlbuild` to the brew formula deps -- though the way the HHVM build system looks for ocamlbuild is pretty broken so hopefully I won't have to fix that. (It actually looks for `ocamlc` and then assumes `ocamlbuild` exists...)

**Comment by akuseru** [comment]
so i added ocamlbuild to the brewfile locally and ran the install again. The results of that are in that log file that i posted above. looks like it's complaining about stuff from `fsevents_stubs.c`

**Comment by jwatzman** [comment]
Ah it looks like my good friend https://github.com/facebook/hhvm/commit/fa8f120a090ab37318fc8ee1cd88d364b75d3150 again. I'll look for a better fix.

**Comment by jwatzman** [comment]
Yeah I can prob gate on `OCAML_VERSION_MAJOR >= 4 && OCAML_VERSION_MINOR >= 3`.

**Comment by akuseru** [comment]
```Summary: Broke with ocaml 4.01, and we don't build with 4.03 for other
reasons anyways.```

since homebrew now ships 4.03 will this cause other problems in the build? if so would it be better to make use of a separate ocaml formula.

**Comment by jwatzman** [comment]
I managed to work through the other 4.03 issues, and I think still keep us compatible with 4.01/4.02. I'll try to get it landed next week.

**Comment by Orvid** [comment]
I believe we're looking into upgrading to 4.03 internally, @int3 may have more context on that side of things.

**Comment by gabelevi** [comment]
Homebrew is forcing the Flow team to support 4.03 too.

**Comment by jwatzman** [comment]
This specific issue is fixed with 4.03, and the others are coming in a change from @gabelevi :)

**Comment by ignacvucko** [comment]
I was facing the same issue. Tried building against latest head and it still fails for me on Mac OS X 10.11.4

~$ brew install hhvm --HEAD
==> Installing hhvm from hhvm/hhvm
==> Cloning https://github.com/facebook/hhvm.git
Updating /Library/Caches/Homebrew/hhvm--git
==> Checking out branch master
Synchronizing submodule url for 'brotli/src'
Synchronizing submodule url for 'folly/src'
Synchronizing submodule url for 'mcrouter/src'
Synchronizing submodule url for 'proxygen/src'
Synchronizing submodule url for 're2/src'
Synchronizing submodule url for 'squangle/src'
Synchronizing submodule url for 'thrift/src'
Synchronizing submodule url for 'wangle/src'
Synchronizing submodule url for 'webscalesqlclient/mysql-5.6'
Synchronizing submodule url for 'terryfy'
Synchronizing submodule url for 'rocksdb'
==> Downloading https://github.com/facebook/hhvm/commit/fead9b7c43b03f4b3d711019bc6395ef140f265c.patch
Already downloaded: /Library/Caches/Homebrew/hhvm--patch-8245b7da1804d8afe8a24f3e079a46829927cdd1fcf7335b9147dabf3d60c92f.patch
==> Patching
==> Applying fead9b7c43b03f4b3d711019bc6395ef140f265c.patch
patching file hphp/hack/hhi/Makefile
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file hphp/hack/hhi/Makefile.rej
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1 -i /private/tmp/hhvm--patch-20160512-44668-9b68am/fead9b7c43b03f4b3d711019bc6395ef140f265c.patch

~$ brew gist-logs hhvm
Error: No logs.

Help.
Ignac

**Comment by jwatzman** [comment]
> ==> Applying fead9b7.patch
patching file hphp/hack/hhi/Makefile
Hunk #1 FAILED at 1.

Oops, I need to make that patch not apply to head too.

**Comment by jwatzman** [comment]
Unfortunately this is only fixed for the bits of Hack that Flow uses, there are still some outstanding issues. I hope to be able to get to it this weekend...

**Comment by ignacvucko** [comment]
Hi,

Thanks for your fix.  I now get:

~$ brew install hhvm --HEAD
==> Installing hhvm from hhvm/hhvm
==> Cloning https://github.com/facebook/hhvm.git
Updating /Library/Caches/Homebrew/hhvm--git
==> Checking out branch master
Synchronizing submodule url for 'brotli/src'
Synchronizing submodule url for 'folly/src'
Synchronizing submodule url for 'mcrouter/src'
Synchronizing submodule url for 'proxygen/src'
Synchronizing submodule url for 're2/src'
Synchronizing submodule url for 'squangle/src'
Synchronizing submodule url for 'thrift/src'
Synchronizing submodule url for 'wangle/src'
Synchronizing submodule url for 'webscalesqlclient/mysql-5.6'
Synchronizing submodule url for 'terryfy'
Synchronizing submodule url for 'rocksdb'
==> Downloading https://github.com/facebook/hhvm/commit/fead9b7c43b03f4b3d711019bc6395ef140f265c.patch
Already downloaded: /Library/Caches/Homebrew/hhvm--patch-8245b7da1804d8afe8a24f3e079a46829927cdd1fcf7335b9147dabf3d60c92f.patch
==> Patching
==> Applying fead9b7c43b03f4b3d711019bc6395ef140f265c.patch
patching file hphp/hack/hhi/Makefile
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file hphp/hack/hhi/Makefile.rej
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1 -i /private/tmp/hhvm--patch-20160516-28640-1vkcyew/fead9b7c43b03f4b3d711019bc6395ef140f265c.patch

**Comment by jwatzman** [comment]
I'm still in the process of working on this; it isn't fully fixed yet.

**Comment by jwatzman** [comment]
I have three more diffs up internally to try to fix this.

**Comment by jwatzman** [comment]
OK, should be fixed for `--HEAD`. I'll look into getting the stable release fixed later.

**Comment by mlaurense** [comment]
I just compiled this on my Macbook using `brew install hhvm --HEAD` and can confirm this works. Thanks!

**Comment by ignacvucko** [comment]
Thanks for your changes jwatzman, unfortunately unline mlaurense I still get an error (I tried 2x).
Any ideas?

~$ brew install hhvm --HEAD
==> Installing hhvm from hhvm/hhvm
==> Cloning https://github.com/facebook/hhvm.git
Updating /Library/Caches/Homebrew/hhvm--git
==> Checking out branch master
Synchronizing submodule url for 'brotli/src'
Synchronizing submodule url for 'folly/src'
Synchronizing submodule url for 'mcrouter/src'
Synchronizing submodule url for 'proxygen/src'
Synchronizing submodule url for 're2/src'
Synchronizing submodule url for 'squangle/src'
Synchronizing submodule url for 'thrift/src'
Synchronizing submodule url for 'wangle/src'
Synchronizing submodule url for 'webscalesqlclient/mysql-5.6'
Synchronizing submodule url for 'terryfy'
Synchronizing submodule url for 'rocksdb'
==> Downloading https://github.com/facebook/hhvm/commit/fead9b7c43b03f4b3d711019bc6395ef140f265c.patch
Already downloaded: /Library/Caches/Homebrew/hhvm--patch-8245b7da1804d8afe8a24f3e079a46829927cdd1fcf7335b9147dabf3d60c92f.patch
==> Patching
==> Applying fead9b7c43b03f4b3d711019bc6395ef140f265c.patch
patching file hphp/hack/hhi/Makefile
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file hphp/hack/hhi/Makefile.rej
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1 -i /private/tmp/hhvm--patch-20160518-97173-nga8sj/fead9b7c43b03f4b3d711019bc6395ef140f265c.patch

**Comment by jwatzman** [comment]
@ignacvucko I fixed that a week or two ago, try `brew update` first and make sure it updates your hhvm tap git repo.

**Comment by jwatzman** [comment]
OK, this is *finally* fixed for the stable release. `--HEAD` just broke a few hours ago, but a commit should be out in the next couple of hours to fix it again.

**Comment by ignacvucko** [comment]
It built great - thanks!
I have dozens of library dependencies that it doesn't like (out of date 7.0.0 vs required 8.0.0).
I have been trying to manually fix these one by one by download packages, finding the lib, and symlinking the lib.  Is there an easier way??

**Comment by jwatzman** [comment]
>  I have dozens of library dependencies that it doesn't like (out of date 7.0.0 vs required 8.0.0).

Can you [open a new issue about this](https://github.com/hhvm/homebrew-hhvm/issues), including logs etc elaborating on what you mean?

**Comment by atdt** [comment]
Thanks for working on this, @jwatzman. It's great to have HHVM locally  again.
