### ISSUE TITLE
JSON test suite failure with json-c

### ISSUE THREAD

**Issue by mmuehlenhoff** [facebook/hhvm#7708]
I'm in the process of updating the Debian package of HHVM to 3.18.1. It's building with -DUSE_JSON_C=ON, but with json-c 0.12.1 (the latest available version), the build fails with the test case failures below:

I also tried the build with json-c 0.11, which makes only the json_bigint.php test fail, but not json_last_error_scalar.php.

Let me know if you need additional information.

FAILED: hphp/test/quick/json_bigint.php
003+ int(9223372036854775807)
004+ int(9223372036854775807)
003- float(8.0123456789012E+19)
004- float(9.0123456789012E+19)
...
FAILED: hphp/test/quick/json_last_error_scalar.php
020+ float(0,45)
020- float(0.45)
023+ float(-0,5)
023- float(-0.5)
...................................................................................................................................................................................................................................................................................................................................................................................................
2 tests failed
(◈°◈°◈ ◈◈  ┴─┴

See the diffs:
cat hphp/test/quick/json_bigint.php.diff
cat hphp/test/quick/json_last_error_scalar.php.diff

For xargs, list of failures is available using:
cat /tmp/test-failuresj86uTe

For xargs, list of passed tests is available using:
cat /tmp/tests-passedfEoEST

Run these by hand:
./hphp/hhvm/hhvm -c /home/jmm/git/debian/hhvm/hphp/test/config.ini -vEval.EnableArgsInBacktraces=true -vEval.EnableIntrinsicsExtension=true -vRepo.Local.Mode=-- -vRepo.Central.Path=/home/jmm/git/debian/hhvm/hphp/hhvm/verify.hhbc -vEval.Jit=true   -vEval.ProfileHWEnable=false  -vResourceLimit.CoreFileSize=0   -vEval.SimpleJsonMaxLength=2097152  --file 'hphp/test/quick/json_bigint.php'
./hphp/hhvm/hhvm -c /home/jmm/git/debian/hhvm/hphp/test/config.ini -vEval.EnableArgsInBacktraces=true -vEval.EnableIntrinsicsExtension=true -vRepo.Local.Mode=-- -vRepo.Central.Path=/home/jmm/git/debian/hhvm/hphp/hhvm/verify.hhbc -vEval.Jit=true   -vEval.ProfileHWEnable=false  -vResourceLimit.CoreFileSize=0    --file 'hphp/test/quick/json_last_error_scalar.php'

Re-run just the failing tests:
hphp/test/run --mode 'jit' --threads 2 'hphp/test/quick/json_bigint.php' 'hphp/test/quick/json_last_error_scalar.php'

**Comment by mofarrell** [comment]
I think the option should be `-DUSE_JSONC=true`, but I assume that isn't the issue given that it looks like it was compiling with jsonc.

The first issue seems to be caused by this
https://github.com/facebook/hhvm/blob/master/hphp/runtime/ext/json/jsonc_parser.cpp#L184
not parsing the number as a double.

The second one is because of your locale.  You should run in a shell using `en_US.UTF8` or similar:
```
<?php
var_dump(setlocale(LC_ALL, 0));
var_dump(setlocale(LC_NUMERIC, 0));
```

**Comment by mofarrell** [comment]
This should be fixed in master with https://github.com/facebook/hhvm/commit/f7a1dae3d90179c10c03e749875aa8a6a5015605
Comment if there are still issues.

**Comment by mmuehlenhoff** [comment]
This still occurs with 3.21. I'm getting:

Running 1136 tests in 8 threads (0 in serial)
............................................................................................................s.............................................................FAILED: /tmp/buildd/hhvm-3.21.0+dfsg/hphp/test/quick/json_bigint.php
003+ float(9.2233720368548E+18)
004+ float(9.2233720368548E+18)
003- float(8.0123456789012E+19)
004- float(9.0123456789012E+19)

**Comment by mofarrell** [comment]
Makes sense.  The fix is slightly off.  It needs to reparse the json string as a double, because jsonc converts overflowing ints to INT_MIN or INT_MAX in its internal representation.  As is, it is just casting it to a double.

**Comment by lexidor** [comment]
Support for the json-c parser was removed in https://github.com/facebook/hhvm/commit/ef919bb81cc2326a24d07bb9b7b7574eced09366
